import { useState, useEffect } from 'react';
import api from '../../api/axios';
import StatCard from '../../components/shared/StatCard';
import PageHeader from '../../components/shared/PageHeader';
import StatusBadge from '../../components/shared/StatusBadge';
import { CheckSquare, Receipt, Banknote, Users } from 'lucide-react';

const monthNames = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export default function PayrollDashboard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/dashboard/payroll').then(res => setData(res.data.data)).catch(console.error).finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="space-y-6"><PageHeader title="Payroll Dashboard" /><div className="grid grid-cols-4 gap-4">{[...Array(4)].map((_, i) => <div key={i} className="h-28 bg-slate-800/50 rounded-xl animate-pulse" />)}</div></div>;

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader title="Payroll Dashboard" subtitle="Payroll and compensation overview" />

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard title="Pending Approvals" value={data?.pending_leave_approvals || 0} icon={CheckSquare} color="amber" />
        <StatCard title="This Month Payrun" value={data?.this_month_payrun?.status || 'Not Generated'} icon={Receipt} color="blue" />
        <StatCard title="Payroll Cost" value={`₹${(data?.total_payroll_cost_this_month || 0).toLocaleString('en-IN')}`} icon={Banknote} color="green" />
        <StatCard title="Employees" value={data?.employees_count || 0} icon={Users} color="purple" />
      </div>

      <div className="glass-card rounded-xl p-5">
        <h3 className="text-sm font-medium text-white mb-4">Recent Payruns</h3>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-slate-800">
                <th className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">Period</th>
                <th className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">Status</th>
                <th className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">Employees</th>
                <th className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">Total Cost</th>
                <th className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">Generated By</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/50">
              {(data?.recent_payruns || []).map(pr => (
                <tr key={pr.id} className="hover:bg-slate-800/30 transition-colors">
                  <td className="px-4 py-3 text-sm text-white">{monthNames[pr.month]} {pr.year}</td>
                  <td className="px-4 py-3"><StatusBadge status={pr.status} /></td>
                  <td className="px-4 py-3 text-sm text-slate-300">{pr.payslip_count}</td>
                  <td className="px-4 py-3 text-sm text-emerald-400 font-medium">₹{parseFloat(pr.total_cost).toLocaleString('en-IN')}</td>
                  <td className="px-4 py-3 text-sm text-slate-300">{pr.generated_by_name}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
