import { useState, useEffect, useCallback } from 'react';
import api from '../../api/axios';
import PageHeader from '../../components/shared/PageHeader';
import { PlayCircle, Download, X, Loader2, Eye } from 'lucide-react';
import { toast } from 'sonner';
import { useSocket } from '../../context/SocketContext';

export default function Payruns() {
  const [payruns, setPayruns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showGen, setShowGen] = useState(false);
  const [genForm, setGenForm] = useState({ month: new Date().getMonth() + 1, year: new Date().getFullYear() });
  const [generating, setGenerating] = useState(false);
  const [viewPayslips, setViewPayslips] = useState(null);
  const [payslips, setPayslips] = useState([]);
  const [loadingSlips, setLoadingSlips] = useState(false);
  const { socket } = useSocket();

  const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];

  const fetchPayruns = useCallback(() => {
    api.get('/payroll/payruns').then(res => { setPayruns(res.data.data); setLoading(false); }).catch(() => setLoading(false));
  }, []);

  useEffect(() => {
    fetchPayruns();
  }, [fetchPayruns]);

  useEffect(() => {
    if (!socket) return;
    const handleUpdate = () => fetchPayruns();
    socket.on('payrun_generated', handleUpdate);
    return () => socket.off('payrun_generated', handleUpdate);
  }, [socket, fetchPayruns]);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    try {
      const res = await api.post('/payroll/payrun/generate', genForm);
      toast.success(`Payrun generated! ${res.data.data.payslips_generated_count} payslips created.`);
      setShowGen(false);
      const r = await api.get('/payroll/payruns');
      setPayruns(r.data.data);
    } catch (err) { toast.error(err.response?.data?.message || 'Failed'); }
    setGenerating(false);
  };

  const openPayslips = async (payrun) => {
    setViewPayslips(payrun);
    setLoadingSlips(true);
    try {
      const res = await api.get(`/payroll/payruns/${payrun.id}/payslips`);
      setPayslips(res.data.data);
    } catch { /* empty */ }
    setLoadingSlips(false);
  };

  const downloadPDF = async (payslipId) => {
    try {
      const res = await api.get(`/payroll/payslips/${payslipId}/pdf`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `payslip_${payslipId}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch { toast.error('Failed to download PDF'); }
  };

  return (
    <div className="space-y-6">
      <PageHeader title="Payruns" subtitle="Generate and manage monthly payruns.">
        <button onClick={() => setShowGen(true)} className="btn-glow flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white" style={{ background: 'linear-gradient(135deg,#4d8eff,#571bc1)' }}>
          <PlayCircle className="w-4 h-4" /> Generate Payrun
        </button>
      </PageHeader>

      <div className="glass-panel rounded-2xl overflow-hidden fade-in">
        <table className="w-full glass-table">
          <thead><tr><th>Month / Year</th><th>Status</th><th>Employees</th><th>Total Cost</th><th>Generated By</th><th>Actions</th></tr></thead>
          <tbody>
            {loading ? Array.from({length:3}).map((_,i) => <tr key={i}>{Array.from({length:6}).map((_,j)=><td key={j}><div className="skeleton h-4 w-20 rounded"/></td>)}</tr>) :
            payruns.length === 0 ? <tr><td colSpan={6} className="text-center py-12 text-on-surface-variant">No payruns yet</td></tr> :
            payruns.map(p => (
              <tr key={p.id}>
                <td className="font-medium text-on-surface">{months[p.month - 1]} {p.year}</td>
                <td><span className={`chip-${p.status} inline-flex px-2 py-0.5 rounded-full text-xs font-semibold capitalize`}>{p.status}</span></td>
                <td>{p.employee_count}</td>
                <td className="text-primary font-semibold">₹{parseFloat(p.total_cost || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}</td>
                <td className="text-on-surface-variant">{p.generated_by_name || '—'}</td>
                <td><button onClick={() => openPayslips(p)} className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium text-primary hover:bg-primary/10 transition-colors"><Eye className="w-3.5 h-3.5" /> View Payslips</button></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {showGen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setShowGen(false)}>
          <div className="glass-panel-elevated w-full max-w-sm p-6 fade-in" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold text-on-surface">Generate Payrun</h2>
              <button onClick={() => setShowGen(false)} className="p-1.5 rounded-lg hover:bg-white/5"><X className="w-4 h-4" /></button>
            </div>
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <label className="block text-xs uppercase tracking-widest font-semibold text-on-surface-variant mb-1.5">Month</label>
                <select value={genForm.month} onChange={e => setGenForm(f => ({ ...f, month: parseInt(e.target.value) }))} className="input-glass w-full px-3 py-2 text-sm rounded-xl">
                  {months.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-xs uppercase tracking-widest font-semibold text-on-surface-variant mb-1.5">Year</label>
                <input type="number" value={genForm.year} onChange={e => setGenForm(f => ({ ...f, year: parseInt(e.target.value) }))} className="input-glass w-full px-3 py-2 text-sm rounded-xl" />
              </div>
              <button type="submit" disabled={generating} className="btn-glow w-full py-2.5 rounded-xl text-sm font-semibold text-white disabled:opacity-50" style={{ background: 'linear-gradient(135deg,#4d8eff,#571bc1)' }}>
                {generating ? <Loader2 className="w-4 h-4 animate-spin mx-auto" /> : 'Generate'}
              </button>
            </form>
          </div>
        </div>
      )}

      {viewPayslips && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm" onClick={() => setViewPayslips(null)}>
          <div className="glass-panel-elevated w-full max-w-4xl max-h-[85vh] p-6 overflow-y-auto fade-in" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-5">
              <h2 className="text-lg font-bold text-on-surface">Payslips — {months[viewPayslips.month - 1]} {viewPayslips.year}</h2>
              <button onClick={() => setViewPayslips(null)} className="p-1.5 rounded-lg hover:bg-white/5"><X className="w-4 h-4" /></button>
            </div>
            <table className="w-full glass-table">
              <thead><tr><th>Employee</th><th>Basic</th><th>Gross</th><th>Deductions</th><th>Net Pay</th><th>Actions</th></tr></thead>
              <tbody>
                {loadingSlips ? Array.from({length:5}).map((_,i) => <tr key={i}>{Array.from({length:6}).map((_,j)=><td key={j}><div className="skeleton h-4 w-16 rounded"/></td>)}</tr>) :
                payslips.map(ps => (
                  <tr key={ps.id}>
                    <td className="font-medium text-on-surface">{ps.full_name}</td>
                    <td>₹{parseFloat(ps.basic).toLocaleString()}</td>
                    <td>₹{parseFloat(ps.gross_salary).toLocaleString()}</td>
                    <td className="text-danger">₹{parseFloat(ps.total_deductions).toLocaleString()}</td>
                    <td className="text-primary font-semibold">₹{parseFloat(ps.net_pay).toLocaleString()}</td>
                    <td><button onClick={() => downloadPDF(ps.id)} className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs font-medium text-tertiary hover:bg-tertiary/10 transition-colors"><Download className="w-3.5 h-3.5" /> PDF</button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
