import { useState, useEffect } from 'react';
import api from '../../api/axios';
import PageHeader from '../../components/shared/PageHeader';
import StatusBadge from '../../components/shared/StatusBadge';
import { Plus, Eye, Download, X, Loader2 } from 'lucide-react';

const monthNames = ['','January','February','March','April','May','June','July','August','September','October','November','December'];

export default function Payruns() {
  const [payruns, setPayruns] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showGenerate, setShowGenerate] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [genForm, setGenForm] = useState({ month: new Date().getMonth()+1, year: new Date().getFullYear() });
  const [viewPayslips, setViewPayslips] = useState(null);
  const [payslips, setPayslips] = useState([]);
  const [payslipsLoading, setPayslipsLoading] = useState(false);

  const fetchPayruns = async () => {
    try { const res = await api.get('/payroll/payruns'); setPayruns(res.data.data); }
    catch(e){console.error(e);} finally{setLoading(false);}
  };
  useEffect(()=>{fetchPayruns();},[]);

  const handleGenerate = async (e) => {
    e.preventDefault(); setGenerating(true);
    try { await api.post('/payroll/payrun/generate', genForm); setShowGenerate(false); fetchPayruns(); }
    catch(err){alert(err.response?.data?.message||'Failed');}
    finally{setGenerating(false);}
  };

  const handleViewPayslips = async (payrunId) => {
    setViewPayslips(payrunId); setPayslipsLoading(true);
    try { const res = await api.get(`/payroll/payruns/${payrunId}/payslips`); setPayslips(res.data.data); }
    catch(e){console.error(e);} finally{setPayslipsLoading(false);}
  };

  const handleDownloadPDF = async (payslipId) => {
    try {
      const res = await api.get(`/payroll/payslips/${payslipId}/pdf`, {responseType:'blob'});
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const a = document.createElement('a'); a.href=url; a.download=`payslip.pdf`; a.click();
      window.URL.revokeObjectURL(url);
    } catch(e){alert('Failed to download');}
  };

  const handleFinalize = async (id) => {
    if(!window.confirm('Finalize this payrun?')) return;
    try { await api.patch(`/payroll/payruns/${id}/finalize`); fetchPayruns(); }
    catch(err){alert(err.response?.data?.message||'Failed');}
  };

  return (
    <div className="space-y-6 animate-fadeIn">
      <PageHeader title="Payruns" subtitle="Generate and manage payroll runs">
        <button onClick={()=>setShowGenerate(true)} className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium">
          <Plus className="w-4 h-4"/>Generate Payrun
        </button>
      </PageHeader>

      <div className="glass-card rounded-xl overflow-hidden">
        <table className="w-full">
          <thead><tr className="border-b border-slate-800">
            {['Period','Status','Employees','Total Cost','Generated By','Actions'].map(h=>(
              <th key={h} className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">{h}</th>
            ))}
          </tr></thead>
          <tbody className="divide-y divide-slate-800/50">
            {loading ? [...Array(3)].map((_,i)=><tr key={i}><td colSpan={6}><div className="h-12 bg-slate-800/50 rounded animate-pulse m-2"/></td></tr>) :
              payruns.map(pr=>(
                <tr key={pr.id} className="hover:bg-slate-800/30">
                  <td className="px-4 py-3 text-sm text-white font-medium">{monthNames[pr.month]} {pr.year}</td>
                  <td className="px-4 py-3"><StatusBadge status={pr.status}/></td>
                  <td className="px-4 py-3 text-sm text-slate-300">{pr.payslip_count}</td>
                  <td className="px-4 py-3 text-sm text-emerald-400 font-medium">₹{parseFloat(pr.total_cost).toLocaleString('en-IN')}</td>
                  <td className="px-4 py-3 text-sm text-slate-300">{pr.generated_by_name}</td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <button onClick={()=>handleViewPayslips(pr.id)} className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white" title="View Payslips"><Eye className="w-4 h-4"/></button>
                      {pr.status==='draft' && <button onClick={()=>handleFinalize(pr.id)} className="px-3 py-1 text-xs rounded-lg bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20">Finalize</button>}
                    </div>
                  </td>
                </tr>
              ))}
          </tbody>
        </table>
      </div>

      {showGenerate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-fadeIn">
          <div className="glass-card rounded-2xl p-6 w-full max-w-sm mx-4 shadow-2xl">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-bold text-white">Generate Payrun</h2>
              <button onClick={()=>setShowGenerate(false)} className="p-2 rounded-lg hover:bg-slate-800 text-slate-400"><X className="w-5 h-5"/></button>
            </div>
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <label className="block text-xs uppercase tracking-wide text-slate-500 mb-1.5">Month</label>
                <select value={genForm.month} onChange={e=>setGenForm({...genForm,month:parseInt(e.target.value)})} className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500">
                  {Array.from({length:12},(_,i)=><option key={i} value={i+1}>{monthNames[i+1]}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-xs uppercase tracking-wide text-slate-500 mb-1.5">Year</label>
                <input type="number" value={genForm.year} onChange={e=>setGenForm({...genForm,year:parseInt(e.target.value)})} className="w-full px-3 py-2 bg-slate-800 border border-slate-700 rounded-lg text-sm text-white focus:outline-none focus:border-indigo-500"/>
              </div>
              <div className="flex justify-end gap-3 pt-4">
                <button type="button" onClick={()=>setShowGenerate(false)} className="px-4 py-2 border border-slate-700 rounded-lg text-sm text-slate-300">Cancel</button>
                <button type="submit" disabled={generating} className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-sm font-medium disabled:opacity-50">
                  {generating&&<Loader2 className="w-4 h-4 animate-spin"/>}{generating?'Generating...':'Generate'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {viewPayslips && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm animate-fadeIn">
          <div className="glass-card rounded-2xl p-6 w-full max-w-3xl mx-4 shadow-2xl max-h-[80vh] overflow-y-auto">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-bold text-white">Payslips</h2>
              <button onClick={()=>setViewPayslips(null)} className="p-2 rounded-lg hover:bg-slate-800 text-slate-400"><X className="w-5 h-5"/></button>
            </div>
            {payslipsLoading ? <div className="space-y-3">{[...Array(5)].map((_,i)=><div key={i} className="h-12 bg-slate-800/50 rounded animate-pulse"/>)}</div> : (
              <table className="w-full">
                <thead><tr className="border-b border-slate-800">
                  {['Employee','Basic','Gross','Deductions','Net Pay','PDF'].map(h=>(
                    <th key={h} className="px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-500">{h}</th>
                  ))}
                </tr></thead>
                <tbody className="divide-y divide-slate-800/50">
                  {payslips.map(ps=>(
                    <tr key={ps.id} className="hover:bg-slate-800/30">
                      <td className="px-4 py-3 text-sm text-white">{ps.full_name}</td>
                      <td className="px-4 py-3 text-sm text-slate-300">₹{parseFloat(ps.basic).toLocaleString('en-IN')}</td>
                      <td className="px-4 py-3 text-sm text-slate-300">₹{parseFloat(ps.gross_salary).toLocaleString('en-IN')}</td>
                      <td className="px-4 py-3 text-sm text-red-400">₹{parseFloat(ps.total_deductions).toLocaleString('en-IN')}</td>
                      <td className="px-4 py-3 text-sm text-emerald-400 font-medium">₹{parseFloat(ps.net_pay).toLocaleString('en-IN')}</td>
                      <td className="px-4 py-3"><button onClick={()=>handleDownloadPDF(ps.id)} className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white"><Download className="w-4 h-4"/></button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
